app.py
# ******************************PYTHON LIBRARIES******************************

# ******************************EXTERNAL LIBRARIES****************************
from flask import Flask
# ******************************OWN LIBRARIES*********************************
from routes import blp as CalculatorBlueprint
# ****************************************************************************


def create_app():
    # Framework's instance
    app = Flask(__name__)
    
    # Blueprints registration
    app.register_blueprint(CalculatorBlueprint)
    
    return app


if __name__ == "__main__":
    app = create_app()
    app.run(host="0.0.0.0", port=5000)

routes.py
# ******************************PYTHON LIBRARIES******************************

# ******************************EXTERNAL LIBRARIES****************************
from flask import (request, render_template, Blueprint)
# ******************************OWN LIBRARIES*********************************
from functions import operatorConversor, numToWords
# ****************************************************************************

# Blueprint for the calculator functionalities
blp = Blueprint("calculator", __name__, template_folder="/templates/calculator.html")

# Temporal variables
num_list = []
historial = []
operator = ""
string_number = ""
screen_result = ""
spanish_number = ""
english_number = ""

@blp.route("/calculator", methods=["GET", "POST"])
def calculate():
    # I made the temporal variables 'goblal'
    # in order to access to them from the 
    # method and be able to modify them.
    global num_list, operator, string_number, screen_result, spanish_number, english_number, historial
    
    # Aritmetic operator receiver and coversor
    entered_operator = operatorConversor(request.args.get("operator"))
    # Number receiver
    entered_number = request.args.get("number")
    
    # Artimetic operator's logic
    if entered_operator:
        
        # For the case the user press 'C' for reset
        if entered_operator["name"] == "reset":
            num_list = []
            historial = []
            operator = ""
            string_number = ""
            screen_result = ""
            spanish_number = ""
            english_number = ""
            
        # For the case the user wants to calculate
        # something but there is no formula typed
        elif entered_operator["name"] == "equal" and string_number == "":
            screen_result = ""
            
        # For the case the user wants to calculate
        # something and there is formula typed
        elif entered_operator["name"] == "equal":
            
            # The formula is resolved and delivered
            try:
                equation = string_number
                calc = eval(string_number)
                string_number = str(calc)
                screen_result = string_number
                
                spanish_number = numToWords(string_number, "es")
                english_number = numToWords(string_number, "en")
                historial.append((equation, calc))
                
            # For the case the formula is a zero
            # dividing zero operation
            except ZeroDivisionError:
                screen_result = "\ (T o T) / Boom!"
                
            # For the case the formula do not 
            # represents a valid aritmetic operation
            # or number, for example '8.1.1'
            except SyntaxError:
                screen_result = "X_x Bad syntax!"
                
            # For the case the formula has invalid
            # characters
            except TypeError:
                screen_result = "o_- WTF was that!"
                
            # For the case the translation process
            # of number to text fails due to the 
            # size
            except OverflowError:
                english_number = "\ (T o T) / \t HOLLY SH@#$ are you kiddin' me? I can not eve read it!!"
                spanish_number = "\ (T o T) / \t OSTIAAAS!! Nisiquiera lo puedo leer"
        
        # For the case the user's first choice is a dot
        elif entered_operator["name"] == "dot" and string_number == "":
            string_number += "0."
            screen_result = string_number
            
        # For the case the user's first choice is any 
        # other aritmetic operator different than dot
        elif entered_operator["name"] != "dot" and string_number =="":
            screen_result = string_number
            
        # For the case we already have a formula and
        # the user input an aritmetic operator
        elif entered_operator["name"]:
            string_number += entered_operator["symbol"]
            screen_result = string_number
            
            # For the case the user tries to input two
            # or more aritmetic operators consecutively.
            if string_number[-1] in ["+", "-", "*", "/", "%", "()", ",", ".", "="] and string_number[-2] in ["+", "-", "*", "/", "%", "()", ",", ".", "="]:
                string_number = string_number[:-2]
                string_number = f"{string_number}{entered_operator['symbol']}"
                screen_result = string_number
                
    # Number input logic
    if entered_number:
        string_number += entered_number
        screen_result = string_number
        
    # Render information processed to the 
    # 'calculator.html' template
    return render_template("calculator.html", 
                            screen_result=screen_result, 
                            spanish_number=spanish_number, 
                            english_number=english_number, 
                            historial=historial)

templates/calculator.html
{% from "./macros/macros.html" import historic_calcs %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- INICIO: STYLESHEETS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/style.css') }}">
    <link href="">
    <!-- FIN: STYLESHEETS -->

    <title>Calculator</title>
</head>
<body>
    <main class="content">
        <div class="title__container">
            <h1 class="title">The calculadora</h1>
        </div>

        <div class="tools__container">
            <!-- INICIO: TRADUCTOR -->
            <div class="translator__container">
                <div class="text_box">
                    <div class="text_box__title">English Writting</div>
                    <div class="text_box__traduction"> {{english_number}} </div>
                </div>

                <div class="text_box">
                    <div class="text_box__title">Escritura en Español</div>
                    <div class="text_box__traduction">{{spanish_number}}</div>
                </div>
            </div>
            <!-- FIN: TRADUCTOR -->


            <!-- INICIO: CALCULADORA -->
            <div class="calculator__container">
                <div class="result__container">
                    <p>{{ screen_result }}</p>
                </div>
    
                <div class="numbers__container">
                    <!-- <div> -->
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='reset') }}">C</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='braces') }}">()</a>
                        </div>
                        
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='percentage') }}">%</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='divide') }}">/</a>
                        </div>
                    <!-- </div> -->
    
                    <!-- <div> -->
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='7') }}">7</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='8') }}">8</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='9') }}">9</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='plus') }}">x</a>
                        </div>
                    <!-- </div> -->
                    
                    <!-- <div> -->
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='4') }}">4</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='5') }}">5</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='6') }}">6</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='substract') }}">-</a>
                        </div>
                    <!-- </div> -->
    
                    <!-- <div> -->
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='1') }}">1</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='2') }}">2</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='3') }}">3</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='add') }}">+</a>
                        </div>
                    <!-- </div> -->
    
                    <!-- <div> -->
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='comma') }}">,</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__number" href="{{ url_for('calculator.calculate', number='0') }}">0</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='dot') }}">.</a>
                        </div>
    
                        <div class="keyboard__option">
                            <a class="button__operator" href="{{ url_for('calculator.calculate', operator='equal') }}">=</a>
                        </div>
                    <!-- </div> -->
                </div>
            </div>
            <!-- FIN: CALCULADORA -->

            <!-- INICIO: HISTORIAL -->
            <div class="history__container">
                {% for record in historial %}
                    {{ historic_calcs(record) }}
                {% endfor %}
            </div>
            <!-- FIN: HISTORIAL -->
    </main>
</body>
</html>

templates/macros/macros.html
{%  macro historic_calcs(historial) %}
<div class="historic_register">
    <div class="historic_square">{{ historial[0] }}</div>
    <p>=</p>
    <div class="historic_square">{{ historial[1] }}</div>
</div>
{% endmacro %}